name: pre-commit

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '**'

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: pre-commit/action@v3.0.1
